project_id = "pljnisudnjbfmyffyggm"

[functions.add-team-member]
verify_jwt = false

[functions.list-team-members]
verify_jwt = false

[functions.plaid-create-link-token]
verify_jwt = false

[functions.plaid-exchange-token]
verify_jwt = false

[functions.plaid-get-financials]
verify_jwt = false

[functions.prequal-engine]
verify_jwt = false
